### PR TITLE
moq-pub: JSON catalog support, bugfixes

### PR DESCRIPTION
**Pull request by englishm**
Fixes some bugs around subscription handling and adds support for the new JSON catalog format

### CODE REVIEW

**Comment by englishm** [comment]
cc: @zafergurel. Didn't quite get this working yet, but it's a start!

**Comment by zafergurel** [comment]
@englishm If I can do something to help, please let me know.

**Comment by englishm** [comment]
Ok, after fixing some bugs around subscriber-sent track ids, this hard-coded catalog works for the particular BBB test video I happen to be using. Next I need to make it actually generate real catalogs dynamically by parsing moov headers.

**Comment by englishm** [comment]
Since I've learned the player side isn't currently dependent on all of these fields for playback (it actually still reads them from the init segment), I'm less stressed about working out how to parse all of them from the media itself right now.

Planning to thread through som command line args to set the remaining fields and call this good.

**Comment by zafergurel** [comment]
I got it working on my machine. Thanks! @englishm

**Pull request merged**
